definitions:
  domain.Employee:
    properties:
      department:
        type: string
      name:
        type: string
      role:
        type: string
    required:
    - department
    - name
    - role
    type: object
  domain.Response:
    properties:
      code:
        type: integer
      data: {}
      err:
        type: string
    type: object
info:
  contact: {}
paths:
  /employee/:
    post:
      consumes:
      - application/json
      description: This function is to add an employee to the data base
      parameters:
      - description: Employee details
        in: body
        name: employee
        required: true
        schema:
          $ref: '#/definitions/domain.Employee'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.Response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/domain.Response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/domain.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/domain.Response'
      summary: Add an employee
      tags:
      - Administration
swagger: "2.0"
